// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: segment.proto

package pbLeaf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SegmentFetchNextReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *SegmentFetchNextReq) Reset() {
	*x = SegmentFetchNextReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFetchNextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFetchNextReq) ProtoMessage() {}

func (x *SegmentFetchNextReq) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFetchNextReq.ProtoReflect.Descriptor instead.
func (*SegmentFetchNextReq) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{0}
}

func (x *SegmentFetchNextReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type SegmentFetchNextRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *SegmentFetchNextRes) Reset() {
	*x = SegmentFetchNextRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentFetchNextRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentFetchNextRes) ProtoMessage() {}

func (x *SegmentFetchNextRes) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentFetchNextRes.ProtoReflect.Descriptor instead.
func (*SegmentFetchNextRes) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{1}
}

func (x *SegmentFetchNextRes) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_segment_proto protoreflect.FileDescriptor

var file_segment_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x26, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x69, 0x6d, 0x6b, 0x75,
	0x71, 0x69, 0x6e, 0x5f, 0x7a, 0x77, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6c, 0x65, 0x61, 0x66, 0x22, 0x27, 0x0a, 0x13, 0x53, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67,
	0x22, 0x27, 0x0a, 0x13, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x32, 0x91, 0x01, 0x0a, 0x07, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x85, 0x01, 0x0a, 0x09, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4e,
	0x65, 0x78, 0x74, 0x12, 0x3b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x69, 0x6d, 0x6b, 0x75, 0x71, 0x69, 0x6e, 0x5f, 0x7a, 0x77, 0x2e, 0x63, 0x6f, 0x75, 0x72,
	0x69, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x65, 0x61, 0x66, 0x2e, 0x53, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x3b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x69, 0x6d,
	0x6b, 0x75, 0x71, 0x69, 0x6e, 0x5f, 0x7a, 0x77, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x65, 0x61, 0x66, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x42, 0x0f, 0x5a,
	0x0d, 0x2e, 0x2f, 0x6c, 0x65, 0x61, 0x66, 0x3b, 0x70, 0x62, 0x4c, 0x65, 0x61, 0x66, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_segment_proto_rawDescOnce sync.Once
	file_segment_proto_rawDescData = file_segment_proto_rawDesc
)

func file_segment_proto_rawDescGZIP() []byte {
	file_segment_proto_rawDescOnce.Do(func() {
		file_segment_proto_rawDescData = protoimpl.X.CompressGZIP(file_segment_proto_rawDescData)
	})
	return file_segment_proto_rawDescData
}

var file_segment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_segment_proto_goTypes = []interface{}{
	(*SegmentFetchNextReq)(nil), // 0: com.github.imkuqin_zw.courier.api.leaf.SegmentFetchNextReq
	(*SegmentFetchNextRes)(nil), // 1: com.github.imkuqin_zw.courier.api.leaf.SegmentFetchNextRes
}
var file_segment_proto_depIdxs = []int32{
	0, // 0: com.github.imkuqin_zw.courier.api.leaf.Segment.FetchNext:input_type -> com.github.imkuqin_zw.courier.api.leaf.SegmentFetchNextReq
	1, // 1: com.github.imkuqin_zw.courier.api.leaf.Segment.FetchNext:output_type -> com.github.imkuqin_zw.courier.api.leaf.SegmentFetchNextRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_segment_proto_init() }
func file_segment_proto_init() {
	if File_segment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_segment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFetchNextReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentFetchNextRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_segment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_segment_proto_goTypes,
		DependencyIndexes: file_segment_proto_depIdxs,
		MessageInfos:      file_segment_proto_msgTypes,
	}.Build()
	File_segment_proto = out.File
	file_segment_proto_rawDesc = nil
	file_segment_proto_goTypes = nil
	file_segment_proto_depIdxs = nil
}
