// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.5
// - protoc             v3.12.3
// source: segment.proto

package pbLeaf

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// SegmentClient is the client API for Segment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SegmentClient interface {
	FetchNext(ctx context.Context, in *SegmentFetchNextReq, opts ...grpc_go.CallOption) (*SegmentFetchNextRes, common.ErrorWithAttachment)
}

type segmentClient struct {
	cc *triple.TripleConn
}

type SegmentClientImpl struct {
	FetchNext func(ctx context.Context, in *SegmentFetchNextReq) (*SegmentFetchNextRes, error)
}

func (c *SegmentClientImpl) GetDubboStub(cc *triple.TripleConn) SegmentClient {
	return NewSegmentClient(cc)
}

func (c *SegmentClientImpl) XXX_InterfaceName() string {
	return "com.github.imkuqin_zw.courier.api.leaf.Segment"
}

func NewSegmentClient(cc *triple.TripleConn) SegmentClient {
	return &segmentClient{cc}
}

func (c *segmentClient) FetchNext(ctx context.Context, in *SegmentFetchNextReq, opts ...grpc_go.CallOption) (*SegmentFetchNextRes, common.ErrorWithAttachment) {
	out := new(SegmentFetchNextRes)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/FetchNext", in, out)
}

// SegmentServer is the server API for Segment service.
// All implementations must embed UnimplementedSegmentServer
// for forward compatibility
type SegmentServer interface {
	FetchNext(context.Context, *SegmentFetchNextReq) (*SegmentFetchNextRes, error)
	mustEmbedUnimplementedSegmentServer()
}

// UnimplementedSegmentServer must be embedded to have forward compatible implementations.
type UnimplementedSegmentServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedSegmentServer) FetchNext(context.Context, *SegmentFetchNextReq) (*SegmentFetchNextRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchNext not implemented")
}
func (s *UnimplementedSegmentServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedSegmentServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedSegmentServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &Segment_ServiceDesc
}
func (s *UnimplementedSegmentServer) XXX_InterfaceName() string {
	return "com.github.imkuqin_zw.courier.api.leaf.Segment"
}

func (UnimplementedSegmentServer) mustEmbedUnimplementedSegmentServer() {}

// UnsafeSegmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SegmentServer will
// result in compilation errors.
type UnsafeSegmentServer interface {
	mustEmbedUnimplementedSegmentServer()
}

func RegisterSegmentServer(s grpc_go.ServiceRegistrar, srv SegmentServer) {
	s.RegisterService(&Segment_ServiceDesc, srv)
}

func _Segment_FetchNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentFetchNextReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("FetchNext", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// Segment_ServiceDesc is the grpc_go.ServiceDesc for Segment service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var Segment_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "com.github.imkuqin_zw.courier.api.leaf.Segment",
	HandlerType: (*SegmentServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "FetchNext",
			Handler:    _Segment_FetchNext_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "segment.proto",
}
