// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: snowflake.proto

package pbLeaf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnowflakeFetchNextReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *SnowflakeFetchNextReq) Reset() {
	*x = SnowflakeFetchNextReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snowflake_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnowflakeFetchNextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnowflakeFetchNextReq) ProtoMessage() {}

func (x *SnowflakeFetchNextReq) ProtoReflect() protoreflect.Message {
	mi := &file_snowflake_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnowflakeFetchNextReq.ProtoReflect.Descriptor instead.
func (*SnowflakeFetchNextReq) Descriptor() ([]byte, []int) {
	return file_snowflake_proto_rawDescGZIP(), []int{0}
}

func (x *SnowflakeFetchNextReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type SnowflakeFetchNextRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *SnowflakeFetchNextRes) Reset() {
	*x = SnowflakeFetchNextRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snowflake_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnowflakeFetchNextRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnowflakeFetchNextRes) ProtoMessage() {}

func (x *SnowflakeFetchNextRes) ProtoReflect() protoreflect.Message {
	mi := &file_snowflake_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnowflakeFetchNextRes.ProtoReflect.Descriptor instead.
func (*SnowflakeFetchNextRes) Descriptor() ([]byte, []int) {
	return file_snowflake_proto_rawDescGZIP(), []int{1}
}

func (x *SnowflakeFetchNextRes) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_snowflake_proto protoreflect.FileDescriptor

var file_snowflake_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x26, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x69, 0x6d,
	0x6b, 0x75, 0x71, 0x69, 0x6e, 0x5f, 0x7a, 0x77, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x65, 0x61, 0x66, 0x22, 0x29, 0x0a, 0x15, 0x53, 0x6e, 0x6f,
	0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4e, 0x65, 0x78, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x74, 0x61, 0x67, 0x22, 0x29, 0x0a, 0x15, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b,
	0x65, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x32,
	0x97, 0x01, 0x0a, 0x09, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x12, 0x89, 0x01,
	0x0a, 0x09, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4e, 0x65, 0x78, 0x74, 0x12, 0x3d, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x69, 0x6d, 0x6b, 0x75, 0x71, 0x69, 0x6e,
	0x5f, 0x7a, 0x77, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6c, 0x65, 0x61, 0x66, 0x2e, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x3d, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x69, 0x6d, 0x6b, 0x75, 0x71, 0x69, 0x6e, 0x5f,
	0x7a, 0x77, 0x2e, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c,
	0x65, 0x61, 0x66, 0x2e, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x6c,
	0x65, 0x61, 0x66, 0x3b, 0x70, 0x62, 0x4c, 0x65, 0x61, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_snowflake_proto_rawDescOnce sync.Once
	file_snowflake_proto_rawDescData = file_snowflake_proto_rawDesc
)

func file_snowflake_proto_rawDescGZIP() []byte {
	file_snowflake_proto_rawDescOnce.Do(func() {
		file_snowflake_proto_rawDescData = protoimpl.X.CompressGZIP(file_snowflake_proto_rawDescData)
	})
	return file_snowflake_proto_rawDescData
}

var file_snowflake_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_snowflake_proto_goTypes = []interface{}{
	(*SnowflakeFetchNextReq)(nil), // 0: com.github.imkuqin_zw.courier.api.leaf.SnowflakeFetchNextReq
	(*SnowflakeFetchNextRes)(nil), // 1: com.github.imkuqin_zw.courier.api.leaf.SnowflakeFetchNextRes
}
var file_snowflake_proto_depIdxs = []int32{
	0, // 0: com.github.imkuqin_zw.courier.api.leaf.Snowflake.FetchNext:input_type -> com.github.imkuqin_zw.courier.api.leaf.SnowflakeFetchNextReq
	1, // 1: com.github.imkuqin_zw.courier.api.leaf.Snowflake.FetchNext:output_type -> com.github.imkuqin_zw.courier.api.leaf.SnowflakeFetchNextRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_snowflake_proto_init() }
func file_snowflake_proto_init() {
	if File_snowflake_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snowflake_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnowflakeFetchNextReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snowflake_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnowflakeFetchNextRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snowflake_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snowflake_proto_goTypes,
		DependencyIndexes: file_snowflake_proto_depIdxs,
		MessageInfos:      file_snowflake_proto_msgTypes,
	}.Build()
	File_snowflake_proto = out.File
	file_snowflake_proto_rawDesc = nil
	file_snowflake_proto_goTypes = nil
	file_snowflake_proto_depIdxs = nil
}
