apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $Service$
  name: $Service$
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $Service$
      version: rc-origin
  template:
    metadata:
      labels:
        app: $T-Service$
        version: rc-origin
    spec:
      containers:
        - image: ccr.ccs.tencentyun.com/$Product$/$Service$:latest
          name: $T-Service$