apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $Service$
  name: $Service$
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $Service$
  template:
    metadata:
      labels:
        app: $T-Service$
    spec:
      containers:
        - image: ccr.ccs.tencentyun.com/$Product$/$Service$:latest
          name: $T-Service$
          env:
            - name: "COURIER_DUBBO_CONFIG-CENTER_ADDRESS"
              value: {{.ConfigCenterAddr}}
            - name: "COURIER_DUBBO_CONFIG-CENTER_PROTOCOL"
              value: {{.ConfigCenterProtocol}}