apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: leaf
  name: leaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaf
      version: rc-origin
  template:
    metadata:
      labels:
        app: leaf
        version: rc-origin
    spec:
      containers:
        - image: dockersamples/examplevotingapp_vote:before
          name: vote-e2e
          ports:
            - containerPort: 80
              name: vote